### ISSUE TITLE
Feature request: Select in what worlds will the scoreboard show.

### ISSUE THREAD

**Issue by DvidPiDev** [TheBrunoRM/Skywars#7]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A section in config.yml that would allow us to change in what worlds does the scoreboard show.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Nothing more.

**Comment by TheBrunoRM** [comment]
Ok I will consider this, it seems like a simple implementation. Thank you very much!

**Comment by DvidPiDev** [comment]
Thanks. It is very annoying to see plugins fight over the scoreboard.

**Comment by TheBrunoRM** [comment]
Ok, I just implemented it on ebe5ec5dc562398d23e27b36dd5179253d25dfbe, it should be ready on the next release.
