### ISSUE TITLE
Bug Report: scoreboardWorlds does not actually choose in what worlds will the scoreboard appear.

### ISSUE THREAD

**Issue by DvidPiDev** [TheBrunoRM/Skywars#8]
**Describe the bug**
The newly added feature to select in which worlds will the scoreboard appear, does not work.

**To Reproduce**
Make sure you have a server with 2 or more worlds.
1. Into the config file, type the name of only one world and save it.
2. Start the server and teleport to the world you typed in.
3. You see the scoreboard as expected.
4. Teleport to the other world and you see the scoreboard there too.

**Expected behavior**
Scoreboard only shows in selected worlds.

**Additional context**
Nothing more.

**Screenshots**
![image](https://user-images.githubusercontent.com/79283415/210086036-e07b8772-81a8-47a4-a9cb-efb99d4dde9b.png)
![image](https://user-images.githubusercontent.com/79283415/210086269-f8375f65-548c-4945-905a-174047281cb7.png)
![image](https://user-images.githubusercontent.com/79283415/210086464-10541963-ce20-42f3-b224-c938cfdbc45c.png)

**Versions (please complete the following information):**
 - Plugin version: Latest
 - Server version: 1.19.3
 - Server software: Bukkit (PaperMC Latest)
 - Client version (game version): 1.19.2 (Using ViaVersion)

MORE INFO::
Here is my plugin list if that helps.
![image](https://user-images.githubusercontent.com/79283415/210087114-b6d785b7-a4d1-4b77-a671-358587c91647.png)

Okay, I think I found the issue. I suppose you forgot to remove the example worlds in the SkywarsScoreboard.java file.
![image](https://user-images.githubusercontent.com/79283415/210136435-df77e30e-c831-4061-81a6-0d4a3773e552.png)
I do not code in java so I don't know how to patch that..

**Comment by DvidPiDev** [comment]
My guess would be that it is not formatted properly? I am about to test it.

**Comment by DvidPiDev** [comment]
Happy new year by the way

**Comment by TheBrunoRM** [comment]
Hello and happy new year, I have no tested this. The string you pointed out is the line in the scoreboard.yml, that's the name of the scoreboard. I am going to test and fix this later. Thank you very much for the time!

**Comment by TheBrunoRM** [comment]
Fixed in 4e665c150dd41770e376d6820c21bef558259ac7, the problem was that the code was referencing the wrong configuration file, thus not being able to get the correct list of worlds.

**Comment by DvidPiDev** [comment]
Thanks so much.
